use SENAI_HROADS_TARDE;

INSERT INTO CLASSE(NOME)
VALUES	('BÁRBARO'),
		('CRUZADO'),
		('CAÇADORA'),
		('MONGE'),
		('NECROMANTI'),
		('ARCANISTA'),
		('FEITICEIRO')


INSERT INTO PERSONAGEM(NOME,CAPMAXVIDA,CAPMAXMANA,DATAATUALIZACAO,DATACRIACAO)
VALUES('DEUBUG',100,80,'ATUAL','2018-01-18');
INSERT INTO PERSONAGEM(NOME,CAPMAXVIDA,CAPMAXMANA,DATAATUALIZACAO,DATACRIACAO)
VALUES('BITBUG',70,100,'ATUAL','2016-03-17');
INSERT INTO PERSONAGEM(NOME,CAPMAXVIDA,CAPMAXMANA,DATAATUALIZACAO,DATACRIACAO)
VALUES('FER8',65,70,'ATUAL','2018-03-18');

INSERT INTO TIPOHAB(NOME)
VALUES	('ATAQUE'),
		('DEFESA'),
		('CURA'),
		('MAGIA')

INSERT INTO HABILIDADE(NOME, IDTIPOHAB)
VALUES	('LANÇA MORTAL', 1),
		('ESCUDO SUPREMO', 2),
		('RECUPERAR VIDA', 3)

INSERT INTO INTERMEDIARIA(IDCLASSE,IDHABILIDADE)
VALUES	(1,1),
		(2,2),
		(1,2),
		(3,1),
		(7,3)

UPDATE PERSONAGEM
SET NOME = 'FER7'
WHERE IDPERSONAGEM = 4;

UPDATE CLASSE
SET NOME = 'NECROMANCER'
WHERE IDCLASSE = 5;

