select * FROM PERSONAGEM;

select * FROM CLASSE;

select NOME FROM CLASSE;

SELECT NOME FROM HABILIDADE;

SELECT COUNT (*) AS NOME FROM HABILIDADE;

SELECT IDHABILIDADE FROM HABILIDADE WHERE IDHABILIDADE>=1;

SELECT NOME FROM TIPOHAB;

SELECT HABILIDADE.NOME, TIPOHAB.NOME
FROM HABILIDADE
LEFT JOIN TIPOHAB
ON HABILIDADE.IDTIPOHAB=TIPOHAB.IDTIPOHAB;

SELECT PERSONAGEM.NOME, CLASSE.NOME
FROM PERSONAGEM
LEFT JOIN CLASSE
ON PERSONAGEM.IDCLASSE=CLASSE.IDCLASSE;

SELECT PERSONAGEM.NOME, CLASSE.NOME
FROM PERSONAGEM
FULL OUTER JOIN CLASSE
ON PERSONAGEM.IDCLASSE=CLASSE.IDCLASSE;

SELECT CLASSE.NOME, HABILIDADE.NOME
FROM CLASSE
INNER JOIN HABILIDADE
ON CLASSE.IDCLASSE=HABILIDADE.IDHABILIDADE;

SELECT HABILIDADE.NOME,CLASSE.NOME
FROM HABILIDADE
RIGHT JOIN CLASSE
ON HABILIDADE.IDHABILIDADE=CLASSE.IDCLASSE;