create database SENAI_HROADS_TARDE;

use SENAI_HROADS_TARDE;

create table CLASSE(
	IDCLASSE INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(20),
	);

create table PERSONAGEM(
	IDPERSONAGEM INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(20),
	CAPMAXVIDA TINYINT,
	CAPMAXMANA TINYINT,
	DATAATUALIZACAO VARCHAR(10),
	DATACRIACAO DATE,
	IDCLASSE INT FOREIGN KEY REFERENCES CLASSE(IDCLASSE)
	);

	create table TIPOHAB(
		IDTIPOHAB INT PRIMARY KEY IDENTITY,
		NOME VARCHAR(20),
		);

	create table HABILIDADE(
		IDHABILIDADE INT PRIMARY KEY IDENTITY,
		NOME VARCHAR(20),
		IDTIPOHAB INT FOREIGN KEY REFERENCES TIPOHAB(IDTIPOHAB)
		);

	create table INTERMEDIARIA(
		IDCLASSE INT FOREIGN KEY REFERENCES CLASSE(IDCLASSE),
		IDHABILIDADE INT FOREIGN KEY REFERENCES HABILIDADE(IDHABILIDADE)
		);


